[versions]
# Build tools
android-gradle-plugin = "8.11.1"

kotlin = "2.0.20"
dokka = "1.9.20"
ktlint-gradle = "13.1.0"
versions-plugin = "0.46.0"
android-maven-plugin = "2.1"

# Android
compileSdk = "36"
minSdk = "26"
targetSdk = "36"

# Java/JVM
jvmTarget = "1.8"
javaCompatibility = "1.8"

# Sora SDK
sora-android-sdk = "2025.3.0-canary.2"

# Libraries
libwebrtc = "138.7204.0.2"
gson = "2.13.1"
okhttp = "4.12.0"
kotlinx-coroutines = "1.9.0"
rxjava2 = "2.2.21"
rxandroid2 = "2.1.1"
rxkotlin2 = "2.4.0"

# AndroidX
androidx-appcompat = "1.7.1"
androidx-cardview = "1.0.0"
androidx-recyclerview = "1.4.0"
androidx-constraintlayout = "2.2.1"
androidx-navigation = "2.9.3"
androidx-compose = "1.8.3"
androidx-compose-icons = "1.7.8"
androidx-activity-compose = "1.10.1"

# UI Libraries
material = "1.12.0"
material-spinner = "1.3.1"

# Test libraries
junit = "4.13.2"
androidx-test-core = "1.6.1"
robolectric = "4.15.1"

[libraries]
# Kotlin BOM
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Build tools
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
ben-manes-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions-plugin" }
android-maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "android-maven-plugin" }

# Sora SDK
sora-android-sdk = { module = "com.github.shiguredo:sora-android-sdk", version.ref = "sora-android-sdk" }

# WebRTC & Network
shiguredo-webrtc-android = { module = "com.github.shiguredo:shiguredo-webrtc-android", version.ref = "libwebrtc" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Coroutines & Rx
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxandroid2 = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid2" }
rxkotlin2 = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlin2" }

# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

# Compose
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-icons" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

# UI Libraries
material = { module = "com.google.android.material:material", version.ref = "material" }
material-spinner = { module = "com.jaredrummler:material-spinner", version.ref = "material-spinner" }

# Test libraries
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-maven = { id = "com.github.dcendents.android-maven", version.ref = "android-maven-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }

[bundles]
reactive = ["rxjava2", "rxandroid2", "rxkotlin2"]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-android"]
compose = ["androidx-compose-ui", "androidx-compose-material", "androidx-compose-material-icons", "androidx-activity-compose"]
androidx-navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]
androidx-ui = ["androidx-appcompat", "androidx-cardview", "androidx-recyclerview", "androidx-constraintlayout"]
